#!/bin/sh

# if $DEBUG is set then echo start of aliasrc
[ -n "$DEBUG" ] && echo "start aliasrc"

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx='startx $XINITRC'

# sudo not required for some system commands
# for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
#     alias "$command"="sudo $command"
# done; unset command

# verbose and interactive by default 
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \

 # Alias for copying files and directories with backups and custom suffix
alias rcopy='rsync -aEzhb --info=progress2 --info=stats --info=backup --info=skip --partial'

# Alias for moving files and directories with backups and custom suffix
alias rmove='rsync -aEzhb --info=progress2 --info=stats --info=backup --info=skip --partial --remove-source-files'

# video consumption aliases
alias \
    yt="yt-dlp" \
    ytd="yt-dlp --write-description --write-playlist-metafiles --write-info-json --write-thumbnail --write-subs" \
    ytl="yt-dlp --list-formats" \
    yta="yt-dlp -x -f bestaudio/best --audio-format mp3" \

# Colorize commands when possible.

alias \
    ls="ls -NF --color=auto --group-directories-first" \
    lsl="ls -lhNF --color=auto --group-directories-first" \
    lsh="ls -lahNF --color=auto --group-directories-first" 

# if lsd is installed use these aliases instead
[ -x "$(command -v lsd)" ] &&
alias \
    ls="lsd" \
    lsh="lsd -lA" 

alias \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    less="less  -FgNwW --use-color"

alias arduino="arduino-ide"

# Quick edit various config/dotfiles
alias \
aliasrc='vim $HOME/.config/shell/aliasrc' \
prompt='vim $HOME/.config/shell/.bash_prompt' \
profile='vim $HOME/.config/shell/.profile' \
bashrc='vim $HOME/.bashrc' \
vimrc='vim $HOME/.config/nvim/'

# text to speech 
alias flite="flite_cmu_us_eey"

# cd into ~/Documents/notes then open a new markdown file 
# named as note_ with today's year, month, day, hour, minute
# as part of the file name.
alias note="cd $HOME/Documents/notes && vim note_$(date +%Y%m%d%H%M).md"


# use conf to manage the bare git repo for dotfiles.
# see:
# https://www.atlassian.com/git/tutorials/dotfiles
# https://news.ycombinator.com/item?id=11071754
# https://youtu.be/tBoLDpTWVOM
alias conf='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

# if $DEBUG is set then echo end of aliasrc
[ -n "$DEBUG" ] && echo "end aliasrc"
