#!/bin/sh
echo "start aliasrc"
# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx='startx $XINITRC'

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	ytd="yt-dlp --write-description --write-playlist-metafiles --write-info-json --write-thumbnail --write-subs" \
	ytl="yt-dlp --list-formats" \
	yta="yt-dlp -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"
	#yt="youtube-dl --add-metadata -i" \ 	
# --write-description
# --write-playlist-metafiles
# --write-info-json
# --write-thumbnail 
# --F, --list-formats
# --write-subs

# Colorize commands when possible.
alias \
	ls="lsd" \
	lsh="lsd -la" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"
	# ls="ls -NF --color=auto --group-directories-first" \
	# lsl="ls -lhNF --color=auto --group-directories-first" \
	# lsh="ls -lahNF --color=auto --group-directories-first" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e='$EDITOR' \
	v='$EDITOR' \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

# Quick edit various config/dotfiles
alias \
aliasrc="vim $HOME/.config/shell/aliasrc" \
prompt="vim $HOME/.config/shell/.bash_prompt" \
profile="vim $HOME/.config/shell/.profile" \
bashrc="vim $HOME/.bashrc" \
vimrc="vim $HOME/.config/nvim/"

alias flite="flite_cmu_us_eey"

# use conf to manage the bare git repo for dotfiles.
# see:
# https://www.atlassian.com/git/tutorials/dotfiles
# https://news.ycombinator.com/item?id=11071754
# https://youtu.be/tBoLDpTWVOM
alias conf="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
