
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# unbind = , switch:on:Lid Switch
# unbind = , switch:off:Lid Switch
# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/
 monitor = ,preferred,auto,1
